// exports.catchErrors = (fn) => {
//     return funtion (req,res,next) {
//         return fn(req,res,next).catch(next)
//     }
// }

//här kan jag skapa en trycatch error-grej. finns i anteckningar lektion 8 hur man gör. för att undvika try-catch-block
